- hosts: all
  tasks:
    - name: Set hostname
      become: yes
      ansible.builtin.hostname:
        name: "{{ inventory_hostname|split('.')|first }}.local"
        use: systemd

    - name: Install cert packages
      become: yes
      ansible.builtin.apt:
        name:
          - openssl
          - ssl-cert

    - name: Query snakeoil cert
      ansible.builtin.shell:
        cmd: |
          openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -noout -text |
          grep '\b{{ inventory_hostname }}$'
      failed_when: "false"
      register: cert_grep

    - name: Recreate snakeoil cert
      when: "cert_grep.rc != 0"
      become: yes
      ansible.builtin.command:
        cmd: make-ssl-cert generate-default-snakeoil --force-overwrite

    - name: Fetch snakeoil cert
      ansible.builtin.fetch:
        src: /etc/ssl/certs/ssl-cert-snakeoil.pem
        dest: "{{ inventory_hostname }}.pem"
        flat: true
