- hosts: arvados_cluster_host
  tags:
    - tailscale
  vars:
    cert_check_minute: "{{ 60 | random(seed=inventory_hostname) }}"
    cert_check_dow: "{{ 7 | random(seed=inventory_hostname) }}"
    cert_path: "{{ arvados_tls.Default.cert }}"
    key_path: "{{ arvados_tls.Default.key }}"
  roles:
    - hgram_tailscale_cert

- name: Install Arvados cluster
  ansible.builtin.import_playbook: "{{ arvados_srcdir|default(lookup('ansible.builtin.env', 'HOME') ~ '/arvados') }}/tools/ansible/install-arvados-cluster.yml"

- hosts: arvados_cluster_host
  name: Post-install configuration of APT repos and adding packages
  roles:
    - hgram_distro_apt
  tasks:
    - meta: flush_handlers
    - include_role:
        name: hgram_arvados_tools

- hosts: arvados_cluster_host
  name: Post-install configuration of Docker
  roles:
    - hgram_docker_dns_resolved
