- hosts: arvados_cluster_host
  become: yes
  tags:
    - tailscale
  vars:
    cert_check_minute: "{{ 60 | random(seed=inventory_hostname) }}"
    cert_check_dow: "{{ 7 | random(seed=inventory_hostname) }}"
  tasks:
    - name: Install openssl command line program
      ansible.builtin.package:
        name: openssl
        state: present

    - name: Inspect any existing cert with openssl
      ansible.builtin.command:
        argv:
          - openssl
          - x509
          - -noout
          - -checkend
          - "{{ 10 * 86400 }}"
          - -in
          - "{{ arvados_tls.Default.cert }}"
      register: tailscale_cert_expiry_status
      changed_when: False
      ignore_errors: yes

    - name: Install tailscale cert
      when: tailscale_cert_expiry_status.rc != 0
      ansible.builtin.command:
        argv:
          - tailscale
          - cert
          - "--cert-file={{ arvados_tls.Default.cert }}"
          - "--key-file={{ arvados_tls.Default.key }}"
          - "{{ inventory_hostname }}"

    - name: Install tailscale cert renewal cron job
      ansible.builtin.cron:
        name: "Renew tailscale HTTPS certificates"
        cron_file: tailscale-cert-renew
        user: root
        hour: "0"
        minute: "{{ cert_check_minute }}"
        weekday: "{{ cert_check_dow }}"
        job: "openssl x509 -noout -checkend {{ 8 * 86400 }} -in {{ arvados_tls.Default.cert }} 1> /dev/null 2>&1 || tailscale cert --cert-file={{ arvados_tls.Default.cert }} --key-file={{ arvados_tls.Default.key }} {{ inventory_hostname }}"

- name: Install Arvados cluster
  ansible.builtin.import_playbook: "{{ arvados_srcdir|default(lookup('ansible.builtin.env', 'HOME') ~ '/arvados') }}/tools/ansible/install-arvados-cluster.yml"

- hosts: arvados_cluster_host
  name: Post-install configuration of APT repos and adding packages
  roles:
    - hgram_distro_apt
  tasks:
    - meta: flush_handlers
    - include_role:
        name: hgram_arvados_tools

- hosts: arvados_cluster_host
  name: Post-install configuration of Docker
  roles:
    - hgram_docker_dns_resolved
