- name: Install arvados-client debian package
  hosts: localhost
  tasks:
    - name: Install python-debian into current virtualenv
      ansible.builtin.pip:
        name:
          - python-debian

    - ansible.builtin.include_role:
        name: arvados_apt

    - name: Install arvados-client
      become: yes
      ansible.builtin.apt:
        name:
          - arvados-client
