- hosts: arvados_cluster_host
  tasks:
    - name: Install tailscale cert
      become: yes
      ansible.builtin.command:
        argv:
          - tailscale
          - cert
          - "--cert-file={{ arvados_tls.Default.cert }}"
          - "--key-file={{ arvados_tls.Default.key }}"
          - "{{ inventory_hostname }}"
        creates: "{{ arvados_tls.Default.key }}"

- name: Install Arvados cluster
  ansible.builtin.import_playbook: "{{ arvados_srcdir|default(lookup('ansible.builtin.env', 'HOME') ~ '/arvados') }}/tools/ansible/install-arvados-cluster.yml"

- hosts: arvados_cluster_host
  tasks:
    - name: Install arvados-client (for diagnostics)
      become: yes
      ansible.builtin.apt:
        name: arvados-client
