- name: Populate service facts
  ansible.builtin.service_facts:

- name: Configure Docker and systemd-resolved
  when: ansible_facts['services']['systemd-resolved.service']['status'] == 'enabled'
  become: yes
  block:
  - name: Create systemd-resolved configuration file directory
    ansible.builtin.file:
      path: "/etc/systemd/resolved.conf.d"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Configure systemd-resolved DNS stub listener with Docker daemon
    ansible.builtin.template:
      src: "docker-listener.conf.j2"
      dest: "/etc/systemd/resolved.conf.d/docker-listener.conf"
      owner: root
      group: root
      mode: 0644
    notify:
      - "hgram_docker_dns_resolved : Restart systemd-resolved service"

  - name: Create service drop-in file directory for systemd-resolved service
    ansible.builtin.file:
      path: "/etc/systemd/systemd-resolved.service.d"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Update systemd-resolved drop-in service file
    ansible.builtin.copy:
      dest: "/etc/systemd/systemd-resolved.service.d/after-docker.conf"
      content: |
        [Unit]
        Wants=docker.service
        After=docker.service
      owner: root
      group: root
      mode: 0644
    notify:
      - "hgram_docker_dns_resolved : Restart systemd-resolved service"
